content_blocks_manage_layouttype:
    resource: "@ContentBlocksBundle/Resources/config/routing/layouttype.yml"
    prefix:   /manage/layouttype

content_blocks_manage_contentblocks:
    resource: "@ContentBlocksBundle/Resources/config/routing/contentblock.yml"
    prefix:   /manage/contentblocks

content_blocks_manage_headerblocks:
    resource: "@ContentBlocksBundle/Resources/config/routing/headerblock.yml"
    prefix:   /manage/headerblock