quote_manage_quote:
    resource: "@QuoteBundle/Resources/config/routing/quote.yml"
    prefix:   /manage/quote

quote_manage_quoteversion:
    resource: "@QuoteBundle/Resources/config/routing/quoteversion.yml"
    prefix:   /manage/quoteversion

ajax_organizer_new:
    path:   /ajax/organizer/new
    defaults: { _controller: "TUIToolkitUserBundle:User:new_ajax" }

ajax_institution_new:
    path:   /ajax/institution/new
    defaults: { _controller: "InstitutionBundle:Institution:new_ajax" }

ajax_contentblocks_edit:
    path:   /ajax/contentblocks/edit/{id}/{quoteVersion}/{class}
    defaults: { _controller: "ContentBlocksBundle:ContentBlock:edit" }