user:
    path:     /
    defaults: { _controller: "TUIToolkitUserBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "TUIToolkitUserBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "TUIToolkitUserBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "TUIToolkitUserBundle:User:create" }
    methods:  POST

user_ajax_create:
    path:     /ajax/create
    defaults: { _controller: "TUIToolkitUserBundle:User:ajax_organizer_create" }
    methods:  POST

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "TUIToolkitUserBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "TUIToolkitUserBundle:User:update" }
    methods:  [POST, PUT]

user_upload:
    path:     /{id}/upload
    defaults: { _controller: "TUIToolkitUserBundle:User:createDropZoneForm" }
    methods:  [POST, PUT, GET]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "TUIToolkitUserBundle:User:delete" }
    methods:  [POST, DELETE, GET]

user_quick_delete:
    path:     /{id}/quick_delete
    defaults: { _controller: "TUIToolkitUserBundle:User:quickdelete" }
    methods:  [POST, DELETE, GET]

user_deleted:
    path:     /deleted
    defaults: { _controller: "TUIToolkitUserBundle:User:deleted" }

user_restore:
    path:     /{id}/restore
    defaults: { _controller: "TUIToolkitUserBundle:User:restore" }
    methods:  [POST, PUT, GET]

parent_add_child:
  path: /add/child
  defaults: { _controller: "TUIToolkitUserBundle:User:create" }

user_registration_confirmation:
  path: /{id}/register-confirm-notification
  defaults: {_controller: "TUIToolkitUserBundle:User:registerConfirmationTrigger" }

user_password_reset:
  path: /password/reset/{token}
  defaults: {_controller: "TUIToolkitUserBundle:User:resetPassword" }

user_password_reset_submit:
  path: /password/reset/submit/{id}
  defaults: {_controller: "TUIToolkitUserBundle:User:resetPasswordSubmit" }

register_confirm:
  path: /register/confirm/{token}
  defaults: {_controller: "TUIToolkitUserBundle:User:activateUser" }

activate_user_submit:
  path: /register/{id}/confirm/submit
  defaults: {_controller: "TUIToolkitUserBundle:User:activateUserSubmit" }
  methods:  [POST]

user_password_reset_grid:
  path: /{id}/user-password-reset
  defaults: {_controller: "TUIToolkitUserBundle:User:resetUserPassword" }

user_security_reset:
  path: /{id}/security/reset
  defaults: {_controller: "TUIToolkitUserBundle:User:securityReset" }

user_security_submit:
  path: /{id}/security/submit
  defaults: {_controller: "TUIToolkitUserBundle:User:securitySubmit" }
  methods:  [POST]