
# path for a Quotes Site View, not admin view
quote_site_show:
    path:     /{id}/{quoteNumber}
    defaults: { _controller: "QuoteBundle:QuoteSite:siteShow" }

quote_site_share:
    path:     /share/{id}/{quoteNumber}
    defaults: { _controller: "QuoteBundle:QuoteSite:siteShow" }

quote_site_validate:
    path:     /validate/{id}/
    defaults: { _controller: "QuoteBundle:QuoteSite:siteValidate" }
    methods: [POST]


quote_site_action_show:
    path:     /{id}
    defaults: { _controller: "QuoteBundle:QuoteSite:siteShow" }

