manage_quote:
    path:     /
    defaults: { _controller: "QuoteBundle:QuoteVersion:index" }

manage_quote_show:
    path:     /{id}/show
    defaults: { _controller: "QuoteBundle:Quote:show" }

manage_quote_new:
    path:     /new
    defaults: { _controller: "QuoteBundle:QuoteVersion:new" }

manage_quote_newtemplate:
    path:     /new/template
    defaults: { _controller: "QuoteBundle:QuoteVersion:createtemplate" }

manage_quote_create:
    path:     /create
    defaults: { _controller: "QuoteBundle:Quote:create" }
    methods:  POST

manage_quote_edit:
    path:     /{id}/edit
    defaults: { _controller: "QuoteBundle:QuoteVersion:edit" }

manage_quote_update:
    path:     /{id}/update
    defaults: { _controller: "QuoteBundle:Quote:update" }
    methods:  [POST, PUT]

manage_quote_delete:
    path:     /{id}/delete
    defaults: { _controller: "QuoteBundle:Quote:delete" }
    methods:  [POST, DELETE]

manage_quote_quick_delete:
    path:     /{id}/quick_delete
    defaults: { _controller: "QuoteBundle:Quote:quickdelete" }
    methods:  [POST, DELETE, GET]

manage_quote_active:
    path:     /active
    defaults: { _controller: "QuoteBundle:QuoteVersion:index" }

manage_quote_converted:
    path:     /converted
    defaults: { _controller: "QuoteBundle:QuoteVersion:converted" }

manage_quote_templates:
    path:     /templates
    defaults: { _controller: "QuoteBundle:QuoteVersion:templates" }

manage_quote_deleted:
    path:     /deleted
    defaults: { _controller: "QuoteBundle:QuoteVersion:deleted" }

manage_quote_restore:
    path:     /{id}/restore
    defaults: { _controller: "QuoteBundle:Quote:restore" }