paymenttask:
    path:     /
    defaults: { _controller: "TourBundle:PaymentTask:index" }

paymenttask_show:
    path:     /{id}/show
    defaults: { _controller: "TourBundle:PaymentTask:show" }

paymenttask_new:
    path:     /new
    defaults: { _controller: "TourBundle:PaymentTask:new" }

paymenttask_create:
    path:     /create
    defaults: { _controller: "TourBundle:PaymentTask:create" }
    methods:  POST

paymenttask_edit:
    path:     /{id}/edit
    defaults: { _controller: "TourBundle:PaymentTask:edit" }

paymenttask_update:
    path:     /{id}/update
    defaults: { _controller: "TourBundle:PaymentTask:update" }
    methods:  [POST, PUT]

paymenttask_delete:
    path:     /{id}/delete
    defaults: { _controller: "TourBundle:PaymentTask:delete" }
    methods:  [POST, DELETE]
