imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: toolkit.yml }
    - { resource: sonata.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

    #assetic
    assetic.filter.compass.images_dir: %kernel.root_dir%/cache/images
    assetic.filter.compass.http_path:  /images


framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
      resources:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
    form_themes:
        - '%kernel.root_dir%/Resources/views/form/fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    read_from:            '%kernel.root_dir%/../web/static'
    use_controller: false
    bundles:        [BrandBundle, TUIToolkitUserBundle, QuoteBundle, InstitutionBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass: ~
        compass:  ~
#        yui_js:
#             jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
    assets:
            jquery:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"
                    # - /srv/www/Toolkit/vendor/components/jquery/jquery.min.js
            toolkit:
                inputs:
                    - @AppBundle/Resources/assets/js/toolkit.js
            # jqueryui:
                # inputs:
                    # - "%kernel.root_dir%/../components/jquery-ui/jquery-ui.js"
            # jqueryuicss:
                # inputs:
                    # - "%kernel.root_dir%/../components/jquery-ui/jquery-ui.css"



# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
          json:     Sonata\Doctrine\Types\JsonType
          phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
         auto_mapping: true
         auto_generate_proxy_classes: "%kernel.debug%"
         naming_strategy: doctrine.orm.naming_strategy.underscore
         filters:
             softdeleteable:
                  class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                  enabled: true

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    use_listener:           true
    use_flash_notifications: true
    user_class: TUI\Toolkit\UserBundle\Entity\User
    registration:
            confirmation:
                from_email:
                      address: registration@toolkit.com
                      sender_name: Toolkit Registration

                enabled:    true
                template:   FOSUserBundle:Registration:email.txt.twig
    from_email:
        address:        noreply@toolkit.com
        sender_name:    TUI Toolkit System

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: '%kernel.root_dir%/Resources/views/menus/knp_menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: true
    # the renderer to use, list is also available by default
    default_renderer: twig


###One Uploader Config
#oneup_uploader:
#    mappings:
#        gallery:
#            frontend: dropzone # or any uploader you use in the frontend
#            namer: oneup_uploader.namer.uniqid
#            error_handler: oneup_uploader.error_handler.noop
#        brand:
#            frontend: dropzone
#            namer: oneup_uploader.namer.uniqid
#            error_handler: oneup_uploader.error_handler.noop
#            enable_progress:      true
#            enable_cancelation:   true
#        user:
#            frontend: dropzone
#            namer: oneup_uploader.namer.uniqid
#            error_handler: oneup_uploader.error_handler.noop
#            enable_progress:      true
#            enable_cancelation:   true

stof_doctrine_extensions:
    default_locale: "%locale%"

    # Only used if you activated the Uploadable extension
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       %kernel.root_dir%/../web/uploads

        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter

        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
          softdeleteable: true

genemu_form:
    date: ~
    autocomplete: ~
    image: ~
