imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: toolkit.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    #assetic
    assetic.filter.compass.images_dir: %kernel.root_dir%/cache/images
    assetic.filter.compass.http_path:  /images


framework:
    #esi:             ~
    #translator:      { fallbacks: [%locale%] }
    translator:      { fallbacks: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating: { engines: ['twig', 'php'] }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator: ~


# Twig Configuration
twig:
    globals:
      locale: %locale%
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
    form_themes:
        - '%kernel.root_dir%/Resources/views/form/fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    read_from:      '%kernel.root_dir%/../web'
    use_controller: false
    bundles:        [TourBundle, BrandBundle, TUIToolkitUserBundle, QuoteBundle, InstitutionBundle, MediaBundle, AppBundle, ContentBlocksBundle, TwigBundle, ContentBlocksBundle, PassengerBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass: ~
        compass:  ~
#        yui_js:
#             jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
    assets:
            jquery:
                inputs:
                    - "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"
                    - "%kernel.root_dir%/../components/jquery/jquery.form.js"
                    - @AppBundle/Resources/assets/js/jeditable.js
                    - @AppBundle/Resources/assets/js/jquery.flexslider.js
                    # - /srv/www/Toolkit/vendor/components/jquery/jquery.min.js
            toolkit:
                inputs:
                    - @AppBundle/Resources/assets/js/toolkit.js
                    - @AppBundle/Resources/assets/js/toolkit_mdl.js
                    - @AppBundle/Resources/assets/js/toolkit_colorpicker.js
                    - @AppBundle/Resources/assets/js/toolkit_global.js

            jqueryui:
                inputs:
                    - "%kernel.root_dir%/../src/AppBundle/Resources/public/js/jquery-ui/jquery-ui.js"
#            jqueryuicss:
#                inputs:
#                    - "%kernel.root_dir%/../src/AppBundle/Resources/assets/jquery-ui/jquery-ui.css"

            ckeditorcustomsettings:
                inputs:
                  -   "%kernel.root_dir%/../src/AppBundle/Resources/public/js/ckeditor/config.js"

            toolkit_dropzone:
                inputs:
                    - @AppBundle/Resources/assets/js/toolkit_dropzone.js

            toolkit_siteshow:
                inputs:
                    - @AppBundle/Resources/assets/js/toolkit_siteshow.js

            toolkit_siteshow_edit:
                inputs:
                    - @AppBundle/Resources/assets/js/toolkit_siteshow_edit.js


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
          phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
         auto_mapping: true
         auto_generate_proxy_classes: "%kernel.debug%"
         naming_strategy: doctrine.orm.naming_strategy.underscore
         filters:
             softdeleteable:
                  class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                  enabled: true

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    use_listener:           true
    use_flash_notifications: true
    user_class: TUI\Toolkit\UserBundle\Entity\User
    registration:
            confirmation:
                enabled:    true
                template:   TUIToolkitUserBundle:Registration:register_email.html.twig
    from_email:
        address:        noreply@toolkit.com
        sender_name:    TUI Toolkit System
    resetting:
            email:
                template:   TUIToolkitUserBundle:Resetting:reset.html.twig
#            form:
#                type: tui_user_resetting
            token_ttl: 120  # reset can be done every 2 minutes


knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: '%kernel.root_dir%/Resources/views/menus/knp_menu.html.twig'
    #  if true, enables the helper for PHP templates
    templating: true
    # the renderer to use, list is also available by default
    default_renderer: twig


#One Uploader Config
# reference: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/configuration_reference.md
oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone
            namer: oneup_uploader.namer.uniqid
            error_handler: oneup_uploader.error_handler.noop
            enable_progress:      true
            enable_cancelation:   true
            allowed_mimetypes:
             - image/jpeg
             - image/png
             - image/jpg
            storage:
              directory: "%kernel.root_dir%/../web/static/uploads/media/gallery"
        brand:
            frontend: dropzone
            namer: oneup_uploader.namer.uniqid
            error_handler: oneup_uploader.error_handler.noop
            enable_progress:      true
            enable_cancelation:   true
            allowed_mimetypes:
              - image/jpeg
              - image/png
              - image/jpg
            storage:
              directory: "%kernel.root_dir%/../web/static/uploads/media/brand"
        institution:
            frontend: dropzone
            namer: oneup_uploader.namer.uniqid
            error_handler: oneup_uploader.error_handler.noop
            enable_progress:      true
            enable_cancelation:   true
            allowed_mimetypes:
               - image/jpeg
               - image/png
               - image/jpg
            storage:
              directory: "%kernel.root_dir%/../web/static/uploads/media/institution"
        user:
            frontend: dropzone
            namer: oneup_uploader.namer.uniqid
            error_handler: oneup_uploader.error_handler.noop
            enable_progress:      true
            enable_cancelation:   true
            storage:
              directory: "%kernel.root_dir%/../web/static/uploads/media/user"
            allowed_mimetypes:
              - image/jpeg
              - image/png
              - image/jpg
        contentblock:
            frontend: dropzone
            namer: oneup_uploader.namer.uniqid
            error_handler: oneup_uploader.error_handler.noop
            enable_progress:      true
            enable_cancelation:   true
            storage:
              directory: "%kernel.root_dir%/../web/static/uploads/media/contentblock"
            allowed_mimetypes:
              - image/jpeg
              - image/png
              - image/jpg
        tourassets:
            frontend: dropzone
            namer: oneup_uploader.namer.uniqid
            error_handler: oneup_uploader.error_handler.noop
            enable_progress:      true
            enable_cancelation:   true
            storage:
                directory: "%kernel.root_dir%/../web/static/uploads/media/tourassets"
            allowed_mimetypes:
              - application/msword
              - application/vnd.openxmlformats-officedocument.wordprocessingml.document
              - application/vnd.ms-excel
              - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
              - application/vnd.ms-powerpoint
              - application/vnd.openxmlformats-officedocument.presentationml.presentation
              - application/pdf


stof_doctrine_extensions:
    default_locale: "%locale%"

    # Only used if you activated the Uploadable extension
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       %kernel.root_dir%/../web/uploads

        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter

        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
          softdeleteable: true

genemu_form:
    date: ~
    autocomplete: ~
    image: ~

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers:  ['tuihtmlpurifier'] #['html_purifier']
    toolbar: ['document', 'basicstyles', 'links', 'insert', 'styles', 'paragraph']
    toolbar_groups:
        document: ['Source', 'Undo', 'Redo']
        links: ['Link','Unlink','Anchor']
        insert: ['Embed', 'Image', 'Table']
        styles: ['Styles']
    ui_color: '#ffffff'
    startup_outline_blocks: false
    width: 100% #Integer or %
    height: 300 #Integer or %
    custom_config: "/assetic/ckeditorcustomsettings.js"
    filebrowser_image_upload_url:
            route: _ckeditor_upload
#    filebrowser_image_browse_url:
#            route: elfinder
#            route_parameters:
#                 instance: ckeditor
    external_plugins:
#        youtube:
#            path: "/bundles/app/ckeditor-plugins/youtube"
#        dialog:
#            path: "/bundles/app/ckeditor-plugins/dialog"
#        dialogui:
#            path: "/bundles/app/ckeditor-plugins/dialogui"
        fakeobjects:
            path: "/bundles/app/ckeditor-plugins/fakeobjects"
        filetools:
            path: "/bundles/app/ckeditor-plugins/filetools"
        floatpanel:
            path: "/bundles/app/ckeditor-plugins/floatpanel"
        indent:
            path: "/bundles/app/ckeditor-plugins/indent"
        lineutils:
            path: "/bundles/app/ckeditor-plugins/lineutils"
        listblock:
            path: "/bundles/app/ckeditor-plugins/listblock"
        embedbase:
            path: "/bundles/app/ckeditor-plugins/embedbase"
        menu:
            path: "/bundles/app/ckeditor-plugins/menu"
        menubutton:
            path: "/bundles/app/ckeditor-plugins/menubutton"
        notification:
            path: "/bundles/app/ckeditor-plugins/notification"
        notificationaggregator:
            path: "/bundles/app/ckeditor-plugins/notificationaggregator"
        panel:
            path: "/bundles/app/ckeditor-plugins/panel"
        popup:
            path: "/bundles/app/ckeditor-plugins/popup"
        richcombo:
            path: "/bundles/app/ckeditor-plugins/richcombo"
        button:
            path: "/bundles/app/ckeditor-plugins/button"
        uploadwidget:
            path: "/bundles/app/ckeditor-plugins/uploadwidget"
        widget:
            path: "/bundles/app/ckeditor-plugins/widget"
#        uploadimage:
#            path: "/bundles/app/ckeditor-plugins/uploadimage"
        embed:
            path: "/bundles/app/ckeditor-plugins/embed"
#        imageuploader:
#            path: "/bundles/app/ckeditor-plugins/imageuploader"
        embedsemantic:
            path: "/bundles/app/ckeditor-plugins/embedsemantic"

app:
    html_purifier:
        config:
            HTML.AllowedAttributes: 'alt, src, href, target, colspan, class, style, action, allowfullscreen, frameborder, height, width, border, cellpadding, cellspacing'
            Attr.AllowedFrameTargets: '_blank, _self, _parent, _top'
           # HTML.AllowedElements: ''
            HTML.SafeIframe: true
            HTML.Trusted: true
            HTML.SafeEmbed: true
            HTML.SafeObject: true
            Output.FlashCompat: true
            URI.SafeIframeRegexp: '/(http:|https:)?\/\/(www\.)?(youtube.com|youtu.be)\/(watch)?(\?v=)?(\S+)?/'

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumbnail:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: inset }

        thumbnailLarge:
            quality: 100
            filters:
                thumbnail: { size: [240, 240], mode: inset }

        brandLogo:
            filters:
                relative_resize: { widen: 120 }

        slideShow:
            quality: 100
            filters:
                strip: ~
                thumbnail: { size: [1600, 900], mode: inset }
        modalImage:
            quality: 100
            filters:
                relative_resize: { widen: 300 }

fm_elfinder:
    instances:
        ckeditor:
            locale:  en # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: static/uploads/media/ckeditor
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 32M
