content_blocks:
    resource: "@ContentBlocksBundle/Resources/config/routing.yml"
    prefix:   /

trip_status:
    resource: "@TripStatusBundle/Resources/config/routing.yml"
    prefix:   /

tui_toolkit_board_basis:
    resource: "@BoardBasisBundle/Controller/"
    type:     annotation
    prefix:   /

tui_toolkit_quote:
    resource: "@QuoteBundle/Resources/config/routing.yml"
    prefix:   /

brand:
    resource: "@BrandBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

tui_toolkit_user_user:
    resource: "@TUIToolkitUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

tui_toolkit_transport:
    resource: "@TransportBundle/Resources/config/routing.yml"
    prefix:   /

tui_toolkit_tripstatus:
    resource: "@TripStatusBundle/Resources/config/routing.yml"
    prefix:   /

tui_toolkit_contentblocks:
    resource: "@ContentBlocksBundle/Resources/config/routing.yml"
    prefix:   /

tui_toolkit_institution:
    resource: "@InstitutionBundle/Resources/config/routing.yml"
    prefix:   /

tui_toolkit_currency:
    resource: "@CurrencyBundle/Resources/config/routing.yml"
    prefix:   /

# temporary routes until real ones are implemented
# @todo REMOVE THESE WITH REAL FUNCTIONALITY LATER

_manage_tour_home:
  path: /
_tui_toolkit_reports_modification:
  path: /
_tui_toolkit_reports_opportunity:
  path: /
_tui_toolkit_manage_company_currency:
  path: /


# This is for Sonata Media Bundle
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: uploads/static/media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: uploads/static/media

oneup_uploader:
    resource: .
    type: uploader