tui_toolkit_board_basis:
    resource: "@BoardBasisBundle/Controller/"
    type:     annotation
    prefix:   /

tui_toolkit_quote:
    resource: "@TUIToolkitQuoteBundle/Controller/"
    type:     annotation
    prefix:   /

brand:
    resource: "@BrandBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

tui_toolkit_user_user:
    resource: "@TUIToolkitUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

#tui_toolkit_user:
#    resource:  "@TUIToolkitUserBundle/Resources/config/routing.yml"
#    prefix:   "/user"


# temporary routes until real ones are implemented
# @todo REMOVE THESE WITH REAL FUNCTIONALITY LATER

_manage_tour_home:
  path: /
_tui_toolkit_reports:
  path: /
_tui_toolkit_reports_modification:
  path: /
_tui_toolkit_reports_opportunity:
  path: /
_tui_toolkit_tools:
  path: /
_tui_toolkit_manage_company:
  path: /
_tui_toolkit_manage_company_divisions:
  path: /
_tui_toolkit_manage_company_transport:
  path: /
_tui_toolkit_manage_company_currency:
  path: /
_tui_toolkit_manage_company_institution:
  path: /

# This is for Sonata Media Bundle
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media