security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_USER:        ROLE_USER
            ROLE_CUSTOMER:    ROLE_USER
            ROLE_BRAND:       ROLE_CUSTOMER
            ROLE_ADMIN:       ROLE_BRAND
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                 provider: fos_userbundle
                 check_path:    fos_user_security_check
                 csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                path: /logout
                target: /
            anonymous:    true
            security: true

    access_control:
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/manage/, role: ROLE_BRAND }
            - { path: ^/user/password-set/, role: ROLE_CUSTOMER }
            - { path: ^/user/add/, role: ROLE_CUSTOMER }
            - { path: ^/user/[0-9]+/edit$, role: ROLE_CUSTOMER }
            - { path: ^/user/[0-9]+/update$, role: ROLE_CUSTOMER }
            - { path: ^/user/new, role: ROLE_BRAND }
            - { path: ^/user/, role: ROLE_BRAND }
            - { path: ^/profile/, role: ROLE_CUSTOMER }
            - { path: ^/tour/dashboard, role: ROLE_CUSTOMER }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/efconnect, role: ROLE_USER }
            - { path: ^/elfinder, role: ROLE_USER }


