security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_USER:        ROLE_USER
            ROLE_CUSTOMER:    ROLE_USER
            ROLE_BRAND:       ROLE_CUSTOMER
            ROLE_ADMIN:       ROLE_BRAND
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                 provider: fos_userbundle
                 check_path:    fos_user_security_check
                 csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                path: /logout
                target: /
            anonymous:    true
            security: true

    access_control:
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/manage/contentblocks/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/manage/contentblocks/, role: ROLE_CUSTOMER }
            - { path: ^/manage/headerblock/, role: ROLE_CUSTOMER }
            - { path: ^/manage/, role: ROLE_BRAND }
            - { path: ^/user/password-set/, role: ROLE_CUSTOMER }
            - { path: ^/user/password/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/user/add/, role: ROLE_CUSTOMER }
            - { path: ^/user/[0-9]+/edit$, role: ROLE_CUSTOMER }
            - { path: ^/user/[0-9]+/security, role: ROLE_CUSTOMER }
            - { path: ^/user/[0-9]+/update$, role: ROLE_CUSTOMER }
            - { path: ^/user/new, role: ROLE_BRAND }
            - { path: ^/user/, role: ROLE_BRAND }
            - { path: ^/profile/, role: ROLE_CUSTOMER }
            - { path: ^/tour/dashboard, role: ROLE_CUSTOMER }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/efconnect, role: ROLE_CUSTOMER }
            - { path: ^/elfinder, role: ROLE_CUSTOMER }
            - { path: ^/brand_payment, role: ROLE_BRAND }
            - { path: ^/_ckeditor/upload, role: ROLE_CUSTOMER }
            - { path: ^/_uploader, role: ROLE_CUSTOMER }
            - { path: ^/ajax/institution, role: ROLE_BRAND }
            - { path: ^/ajax/organizer, role: ROLE_BRAND }
            - { path: ^/ajax, role: ROLE_CUSTOMER }
            - { path: ^/brand_payment/[0-9]+/edit$, role: ROLE_SUPER_ADMIN }
            - { path: ^/brand_payment/[0-9]+/show$, role: ROLE_SUPER_ADMIN }
            - { path: ^/genemu_change_image, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/[0-9]+/delete$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/dietary/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/dietary/[0-9]+/delete$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/emergency/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/emergency/[0-9]+/delete$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/medical/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/medical/[0-9]+/delete$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/passport/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/passport/[0-9]+/delete$, role: ROLE_SUPER_ADMIN }
            - { path: ^/passenger/new/[0-9]+$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/passenger/, role: ROLE_CUSTOMER }
            - { path: ^/payment/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/payment/[0-9]+/delete$, role: ROLE_SUPER_ADMIN }
            - { path: ^/payment/[0-9]+/edit$, role: ROLE_SUPER_ADMIN }
            - { path: ^/payment/[0-9]+/show$, role: ROLE_SUPER_ADMIN }
            - { path: ^/payment/, role: ROLE_CUSTOMER }
            - { path: ^/paymenttask/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/paymenttask/[0-9]+/show$, role: ROLE_SUPER_ADMIN }
            - { path: ^/paymenttask/, role: ROLE_CUSTOMER }
            - { path: ^/paymenttaskoverride/$, role: ROLE_SUPER_ADMIN }
            - { path: ^/paymenttaskoverride/[0-9]+/delete$, role: ROLE_SUPER_ADMIN }
            - { path: ^/paymenttaskoverride/, role: ROLE_CUSTOMER }
            - { path: ^/permission, role: ROLE_SUPER_ADMIN }
            - { path: ^/quote/view/summary/edit/[0-9]+$, role: ROLE_BRAND }
            - { path: ^/quote/view/summary/update/[0-9]+$, role: ROLE_BRAND }
            - { path: ^/tour/view/summary/edit/[0-9]+$, role: ROLE_CUSTOMER }
            - { path: ^/tour/view/summary/update/[0-9]+$, role: ROLE_CUSTOMER }
            - { path: ^/tour/view/update/name/[0-9]+$, role: ROLE_CUSTOMER }
