# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

imports:
    - { resource: "@PermissionBundle/Resources/config/services.yml" }
    - { resource: "@ContentBlocksBundle/Resources/config/services.yml" }

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     app.slugger:
        class: AppBundle\Utils\Slugger

     app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
          - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin_menu }

     # create different menu services by reproducing the following, replacing main with menu name
#     app.main_menu:
#        class: Knp\Menu\MenuItem # the service definition requires setting the class
#        factory: ["@app.menu_builder", createAdminMenu] # replace createMainMenu with method name from AppBundle/Menu/MenuBuilder.php
#        #arguments: ["@request_stack", "options"]
#        tags:
#            - { name: knp_menu.menu, alias: admin_menu } # The alias is what is used to retrieve the menu

     twig.extension.intl:
         class: Twig_Extensions_Extension_Intl
         tags:
             - { name: twig.extension }

     tui_toolkit_mediabundle.onupload_listener:
         class: TUI\Toolkit\MediaBundle\EventListener\UploadListener
         tags:
             - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
             - { name: kernel.event_listener, event: oneup_uploader.pre_upload, method: preUpload }
         arguments: ['@doctrine']

     trsteel_ckeditor.form.type:
         class: %trsteel_ckeditor.form.type.class%
         arguments: [@service_container]
         tags:
             - { name: form.type, alias: ckeditor }

     trsteel_ckeditor.transformer.html_purifier:
         class: Trsteel\CkeditorBundle\Form\DataTransformer\HTMLPurifierTransformer
         public: false
         arguments: [%trsteel_ckeditor.html_purifier.config%]
         tags:
             - { name: trsteel_ckeditor.transformer, alias: html_purifier }

     app.twig_extension:
         class: AppBundle\Twig\AppExtension
         public: false
         arguments: ['@service_container']
         tags:
             - { name: twig.extension }