manage_layouttype:
    path:     /
    defaults: { _controller: "ContentBlocksBundle:LayoutType:index" }

manage_layouttype_show:
    path:     /{id}/show
    defaults: { _controller: "ContentBlocksBundle:LayoutType:show" }

manage_layouttype_new:
    path:     /new
    defaults: { _controller: "ContentBlocksBundle:LayoutType:new" }

manage_layouttype_create:
    path:     /create
    defaults: { _controller: "ContentBlocksBundle:LayoutType:create" }
    methods:  POST

manage_layouttype_edit:
    path:     /{id}/edit
    defaults: { _controller: "ContentBlocksBundle:LayoutType:edit" }

manage_layouttype_update:
    path:     /{id}/update
    defaults: { _controller: "ContentBlocksBundle:LayoutType:update" }
    methods:  [POST, PUT]

manage_layouttype_delete:
    path:     /{id}/delete
    defaults: { _controller: "ContentBlocksBundle:LayoutType:delete" }
    methods:  [POST, DELETE]
