trip_status_manage_tripstatus:
    resource: "@TripStatusBundle/Resources/config/routing/tripstatus.yml"
    prefix:   /manage/tripstatus

trip_status_homepage:
    path:     /hello/{name}
    defaults: { _controller: TripStatusBundle:Default:index }
