manage_mediawrapper:
    path:     /
    defaults: { _controller: "MediaBundle:MediaWrapper:index" }

manage_mediawrapper_show:
    path:     /{id}/show
    defaults: { _controller: "MediaBundle:MediaWrapper:show" }

manage_mediawrapper_new:
    path:     /new
    defaults: { _controller: "MediaBundle:MediaWrapper:new" }

manage_mediawrapper_create:
    path:     /create
    defaults: { _controller: "MediaBundle:MediaWrapper:create" }
    methods:  POST

manage_mediawrapper_edit:
    path:     /{id}/edit
    defaults: { _controller: "MediaBundle:MediaWrapper:edit" }

manage_mediawrapper_update:
    path:     /{id}/update
    defaults: { _controller: "MediaBundle:MediaWrapper:update" }
    methods:  [POST, PUT]

manage_mediawrapper_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediaBundle:MediaWrapper:delete" }
    methods:  [POST, DELETE]
