services:
#    tui_toolkit_user.example:
#        class: TUI\Toolkit\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  tui_toolkit_user.form.resetting:
          class: TUI\Toolkit\UserBundle\Form\ResettingFormType
          tags:
              - { name: form.type, alias: tui_user_resetting }
