services:
#    tui_toolkit_user.example:
#        class: TUI\Toolkit\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  tui_toolkit_user.form.resetting:
          class: TUI\Toolkit\UserBundle\Form\ResettingFormType
          tags:
              - { name: form.type, alias: tui_user_resetting }

  tui_toolkit_user.ajax.authentication.listener:
          class: TUI\Toolkit\UserBundle\EventListener\AjaxAuthenticationListener
          arguments: ['@service_container']
          tags:
              - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }
