services:
#    security.access.responsibility_voter:
#        class:      AppBundle\Security\Authorization\Voter\ResponsibilityVoter
#        # set the arguments as an array of responsiblity strings in DESC order,
#        # so that the first string is the name of most authorized and last is least autorized
#        public:     false
#        calls:
#           - [ setContainer,[ @service_container ] ]
#        tags:
#           - { name: security.voter }

  app.transformer.tuihtmlpurifier:
    class: AppBundle\Transformer\TuiHTMLPurifier
    arguments: ['@service_container']
    tags:
      - { name: trsteel_ckeditor.transformer, alias: tuihtmlpurifier}
