manage_passenger:
    path:     /
    defaults: { _controller: "PassengerBundle:Passenger:index" }

manage_passenger_show:
    path:     /{id}/show
    defaults: { _controller: "PassengerBundle:Passenger:show" }

manage_passenger_new:
    path:     /new/{tourId}
    defaults: { _controller: "PassengerBundle:Passenger:new" }

manage_passenger_create:
    path:     /create/{tourId}
    defaults: { _controller: "PassengerBundle:Passenger:create" }
    methods:  POST

manage_passenger_edit:
    path:     /{id}/edit
    defaults: { _controller: "PassengerBundle:Passenger:edit" }

manage_passenger_update:
    path:     /{id}/update
    defaults: { _controller: "PassengerBundle:Passenger:update" }
    methods:  [POST, PUT]

manage_passenger_delete:
    path:     /{id}/delete
    defaults: { _controller: "PassengerBundle:Passenger:delete" }
    methods:  [POST, DELETE]

manager_passenger_dashboard:
    path: /dashboard/{tourId}
    defaults: { _controller: "PassengerBundle:Passenger:getPassengerDashboard" }

manage_waitlist_passenger_dashboard:
    path: /dashboard/{tourId}/waitlist
    defaults: { _controller: "PassengerBundle:Passenger:getWaitlistPassengerDashboard" }

