manage_passenger:
    path:     /
    defaults: { _controller: "PassengerBundle:Passenger:index" }

manage_passenger_show:
    path:     /{id}/show
    defaults: { _controller: "PassengerBundle:Passenger:show" }

manage_passenger_new:
    path:     /new
    defaults: { _controller: "PassengerBundle:Passenger:new" }

manage_passenger_create:
    path:     /create
    defaults: { _controller: "PassengerBundle:Passenger:create" }
    methods:  POST

manage_passenger_edit:
    path:     /{id}/edit
    defaults: { _controller: "PassengerBundle:Passenger:edit" }

manage_passenger_update:
    path:     /{id}/update
    defaults: { _controller: "PassengerBundle:Passenger:update" }
    methods:  [POST, PUT]

manage_passenger_delete:
    path:     /{id}/delete
    defaults: { _controller: "PassengerBundle:Passenger:delete" }
    methods:  [POST, DELETE]
