passenger_manage_passenger:
    resource: "@PassengerBundle/Resources/config/routing/passenger.yml"
    prefix:   /passenger

passenger_homepage:
    path:     /hello/{name}
    defaults: { _controller: PassengerBundle:Default:index }
