services:
#    passenger.example:
#        class: TUI\Toolkit\PassengerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  passenger.actions:
    class: TUI\Toolkit\PassengerBundle\Controller\PassengerService
    arguments: [ @doctrine.orm.entity_manager, @service_container ]