services:
#    passenger.example:
#        class: TUI\Toolkit\PassengerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


  tour.controller:
    class: TUI\Toolkit\TourBundle\Controller\TourController
    arguments: [ @service_container ]